// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkJeNRpPHGr4VNHHZiCwrZl_GlpZ5UW9Y',
    appId: '1:100681275497:web:db9dc60d06a639a8fb2af8',
    messagingSenderId: '100681275497',
    projectId: 'gayux-f5c9e',
    authDomain: 'gayux-f5c9e.firebaseapp.com',
    storageBucket: 'gayux-f5c9e.appspot.com',
    measurementId: 'G-115L8LLNZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5heGH0Rni-DuGuyjvMSinZ7IKIy_Jcns',
    appId: '1:100681275497:android:039721b5d1b0d13bfb2af8',
    messagingSenderId: '100681275497',
    projectId: 'gayux-f5c9e',
    storageBucket: 'gayux-f5c9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0fs0yN2Ap07EgW04zU76O2JHioTKKbHo',
    appId: '1:100681275497:ios:2494736d64680bc0fb2af8',
    messagingSenderId: '100681275497',
    projectId: 'gayux-f5c9e',
    storageBucket: 'gayux-f5c9e.appspot.com',
    androidClientId: '100681275497-2qjnd4rckn8e3ncnq1cmtcnq9tncio1d.apps.googleusercontent.com',
    iosClientId: '100681275497-iask424hj6fljej0dphmku9g1vmbpvn7.apps.googleusercontent.com',
    iosBundleId: 'com.sokofast.btc',
  );
}
